# Generated by Django 3.2.13 on 2022-05-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='theaters',
            field=models.ManyToManyField(null=True, to='app.Theater'),
        ),
    ]
