# Generated by Django 4.0.3 on 2022-03-31 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='total_price',
            new_name='total_amount',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='shown_in_theater',
        ),
        migrations.AddField(
            model_name='theater',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateTimeField(default='', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Born', models.CharField(max_length=50)),
                ('movies_in_theater', models.ManyToManyField(to='app.movie')),
                ('upcoming_movies', models.ManyToManyField(related_name='upcoming', to='app.movie')),
            ],
        ),
    ]
