# Generated by Django 3.2.13 on 2022-05-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_movie_theaters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='theaters',
            field=models.ManyToManyField(to='app.Theater'),
        ),
    ]
