# Generated by Django 4.0.3 on 2022-03-31 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_total_price_seat_total_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='language_avail',
            new_name='language',
        ),
    ]
