# Generated by Django 4.0.3 on 2022-03-31 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_language_avail_movie_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='language',
        ),
    ]
