# Generated by Django 4.0.3 on 2022-04-10 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_movie_cast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(related_name='related_to', to='app.actor'),
        ),
        migrations.AlterField(
            model_name='shows',
            name='movie_shown',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related', to='app.movie'),
        ),
    ]
