# Generated by Django 4.0.3 on 2022-04-17 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_movie_cast_alter_shows_movie_shown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(related_name='related', to='app.actor'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer',
            field=models.URLField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shows',
            name='movie_shown',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.movie'),
        ),
    ]
