# Generated by Django 4.0.3 on 2022-04-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_movie_language_alter_movie_trailer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='upcoming_movies',
        ),
        migrations.AddField(
            model_name='theater',
            name='movies_shown',
            field=models.ManyToManyField(to='app.movie'),
        ),
    ]
