# Generated by Django 4.0.3 on 2022-04-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_movie_cast_alter_movie_trailer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
