# Generated by Django 4.0.3 on 2022-04-24 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_shows_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
