# Generated by Django 4.0.3 on 2022-04-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_actor_upcoming_movies_theater_movies_shown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='movies_in_theater',
        ),
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(to='app.actor'),
        ),
    ]
