# Generated by Django 4.0.3 on 2022-04-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_delete_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theater',
            name='movies_shown',
        ),
        migrations.AddField(
            model_name='movie',
            name='theater',
            field=models.ManyToManyField(to='app.theater'),
        ),
    ]
