# Generated by Django 4.0.3 on 2022-04-28 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_theater_movies_shown_movie_theater'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='theater',
            new_name='theaters',
        ),
    ]
