# Generated by Django 4.0.3 on 2022-04-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_shows_total_seats_seat_total_seats_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='total_seats',
        ),
        migrations.AddField(
            model_name='shows',
            name='total_seats',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_code',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
