# Generated by Django 4.0.3 on 2022-04-29 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0012_remove_seat_total_seats_shows_total_seats_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='total_amount',
        ),
        migrations.AlterField(
            model_name='bookedseat',
            name='booked_by_customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookedseat',
            name='booking_status',
            field=models.CharField(blank=True, choices=[('BOOKED', 'BOOKED'), ('AVAILABLE', 'AVAILABLE')], default='AVAILABLE', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='bookedseat',
            name='seat_code',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bookedseat',
            name='shows',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.shows'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='no_of_seats',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
