# Generated by Django 4.0.3 on 2022-03-25 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=25, null=True)),
                ('duration', models.CharField(default='', max_length=25, null=True)),
                ('genre', models.CharField(default='', max_length=25, null=True)),
                ('release_date', models.CharField(default='', max_length=20, null=True)),
                ('language_avail', models.CharField(max_length=50, null=True)),
                ('trailer', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=30, null=True)),
                ('no_of_screen', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True)),
                ('language', models.CharField(max_length=50, null=True)),
                ('screen', models.IntegerField(default=1)),
                ('datetime', models.DateTimeField(null=True)),
                ('movie_shown', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.movie')),
                ('theater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.theater')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='shown_in_theater',
            field=models.ManyToManyField(to='app.theater'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True)),
                ('phone', models.CharField(max_length=13, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('Debit Card', 'Debit Card'), ('Credit Card', 'Credit Card'), ('Net Banking', 'Net Banking'), ('Wallet', 'Wallet')], default='Debit Card', max_length=11)),
                ('amount_paid', models.IntegerField(null=True)),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.customer')),
                ('paid_for', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.shows')),
            ],
        ),
        migrations.CreateModel(
            name='BookedSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_code', models.CharField(max_length=3, null=True)),
                ('booking_status', models.CharField(choices=[('BOOKED', 'BOOKED'), ('AVAILABLE', 'AVAILABLE'), ('RESERVED', 'RESERVED'), ('NOT_AVAILABLE', 'NOT_AVAILABLE')], default='AVAILABLE', max_length=25, null=True)),
                ('booked_by_customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.customer')),
                ('shows', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.shows')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_seats', models.IntegerField(null=True)),
                ('seat_code', models.CharField(max_length=20, null=True)),
                ('seat_type', models.CharField(choices=[('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum')], max_length=8)),
                ('total_price', models.IntegerField(null=True)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.shows')),
            ],
            options={
                'unique_together': {('seat_code', 'show')},
            },
        ),
    ]
